leftnav:
- identifier: b98fe71b-df77-b6f4-3aa0-d15429da2c58
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: b21b7716-a7bd-5627-0834-6d0c99560af1
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 5c21b144-4bd4-0c9a-f31c-233f23abdcfb
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 3495728e-070e-0a32-0a81-4ef7674da873
  name: Assignments
  url: /pages/assignments
  weight: 40
